[package]
name = "async-bench"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
hyper = "0.11"
serde = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
